### ISSUE TITLE
No songs in library

### ISSUE THREAD

**Issue by smalltock** [stevenewbs/gmpydl#10]
gmpydl tells me I have no songs in my library.  I definitely do have songs.  I'm wondering if anyone else has the same trouble.  I noticed that if I try with google's own music manager program, their own program also tells me I have no songs, so it seems like probably a server-side problem.  Mostly just wondering if others have the same problem.

**Comment by stevenewbs** [comment]
Going to close this as it doesn't sound like an issue here. 
This can only show songs you purchased or uploaded - perhaps that will help...
