### ISSUE TITLE
nothing happens after ./gmpydl

### ISSUE THREAD

**Issue by moore-bryan** [stevenewbs/gmpydl#11]
No errors and nothing downloaded after executing ./gmpydl; just warns me about "Loding library" and then goes back to prompt.

**Comment by stevenewbs** [comment]
Also try running with the -d flag which will redirect output to the terminal.

**Comment by moore-bryan** [comment]
Thanks for the response! The log shows the script complaining about being unable to create directors in the source; however, I own and have the permissions set correctly. Other ideas?

**Comment by stevenewbs** [comment]
Whatever user is running the script would need permissions to create directories in the directory its trying to put the music into (the "dest" setting in the conf file) as well as its own config directory (usually ~/.gmpydl ) where it puts the cache for your library. Which directory is it struggling to create?

**Comment by moore-bryan** [comment]
I've chown-ed and chmod-ed everything to ensure I could do what I needed to
do and ran the script as me; I'm trying to download all music to an
external hd pmounted in /media.

--
*B.Moore*

**Comment by stevenewbs** [comment]
Can you post the error or the log please?

**Comment by moore-bryan** [comment]
Sorry for the delay...
```
2018-02-17 12:36:53.734744 : Writng config to file
2018-02-17 12:36:53.735241 : Music going to /media/Segate/Music/GMD
2018-02-17 12:37:27.994774 : Logging in as moore.bryan@gmail.com
2018-02-17 12:37:41.329405 : 13966 new songs
2018-02-17 12:37:41.329607 : Starting download of Joel, Billy - Modern Woman
2018-02-17 12:37:41.329816 : Error making directory: [Errno 13] Permission denied: '/media/Segate'
```
And that just replicates for every song...

**Comment by stevenewbs** [comment]
Hey sorry not really been giving this much attention of late. 
Still having issues with this? Looks like it was having a problem with writing to the external drive or the "Music" directory

**Comment by moore-bryan** [comment]
This was never resolved for me and I gave up on getting it to work. Perhaps I'll come back to it at a later date and try again.
