### ISSUE TITLE
[ERROR]: upauth failure

### ISSUE THREAD

**Issue by hashworks** [stevenewbs/gmpydl#2]
I'm getting the following after I followed the login procedure: http://ix.io/kni

**Comment by stevenewbs** [comment]
This looks like some kind of error in the google music API that I use in gmpydl:
*Upload auth error code 9: MAX_LIMIT_REACHED. See http://goo.gl/O6xe7 for more information*

Normally gmpydl only does downloading so it does seem a bit odd that you have hit an upload error. It may be worth logging into Music and checking how many devices you have registered on your Google Music account (I think the limit is 10). Its in "Settings". Each PC that runs gmpydl counts as one device and it usually shows up as <devicename>(gmusicapi-4.0.0).

**Comment by hashworks** [comment]
Thanks, that's it. Don't know why I didn't thought of that.

**Comment by aug-riedinger** [comment]
Got the same error! Thanks
