### ISSUE TITLE
Make sure the shebang advices python2

### ISSUE THREAD

**Issue by hashworks** [stevenewbs/gmpydl#3]
F.e. `#!/usr/bin/env python2`
Otherwise it will use python3 on most systems.

**Comment by stevenewbs** [comment]
python2 would certainly ensure that it will use python2 so its probably a good idea - thanks. 
I have yet to use anything that uses python3 by default - but I'm sure its coming.

**Comment by hashworks** [comment]
Pro tip: You can close issues with commits by referencing them like "resolves #3": https://help.github.com/articles/closing-issues-via-commit-messages/
