### ISSUE TITLE
Music added to "Own Music" with Google Music All Access won't be downloaded

### ISSUE THREAD

**Issue by hashworks** [stevenewbs/gmpydl#5]
Currently it only downloads music you actually buyed or uploaded yourself, not music added using Google Music All Access. Is this a bug or something you can add? Otherwise you might want to add this to the readme.

EDIT: Ok, seems like there is actually no legit "download" way for this type, you would have to "listen" to the music and rip it off.

**Comment by stevenewbs** [comment]
All access is "streaming" as opposed to music you "own". 
This is more of a limitation of the service rather than this piece of code.
