### ISSUE TITLE
Ends with error

### ISSUE THREAD

**Issue by bulletfreak** [stevenewbs/gmpydl#6]
At first it actually works fine, this this happens after a while `Follow the prompts, then paste the auth code here and hit enter: ****************************
Traceback (most recent call last):
  File "gmpydl.py", line 220, in <module>
    main()
  File "gmpydl.py", line 204, in main
    download_song(api, s)                                                                                                                                                           
  File "gmpydl.py", line 172, in download_song                                                                                                                                      
    filename, audio = api.download_song(songdata['id'])                                                                                                                             
  File "<decorator-gen-65>", line 2, in download_song                                                                                                                               
  File "/usr/lib64/python2.7/site-packages/gmusicapi-10.0.2rc1-py2.7.egg/gmusicapi/utils/utils.py", line 296, in wrapper                                                            
    return function(*args, **kw)                                                                                                                                                    
  File "/usr/lib64/python2.7/site-packages/gmusicapi-10.0.2rc1-py2.7.egg/gmusicapi/clients/musicmanager.py", line 372, in download_song                                             
    response = self._make_call(musicmanager.DownloadTrack, url)                                                                                                                     
  File "/usr/lib64/python2.7/site-packages/gmusicapi-10.0.2rc1-py2.7.egg/gmusicapi/clients/shared.py", line 84, in _make_call                                                       
    return protocol.perform(self.session, self.validate, *args, **kwargs)                                                                                                           
  File "/usr/lib64/python2.7/site-packages/gmusicapi-10.0.2rc1-py2.7.egg/gmusicapi/protocol/shared.py", line 228, in perform                                                        
    raise CallFailure(err_msg, call_name)                                                                                                                                           
gmusicapi.exceptions.CallFailure: DownloadTrack: 500 Server Error: Internal Server Error for url: https://sj.googleusercontent.com/download?id=f7d4c9b86874da5d&itag=25&source=skyjam_user_upload&o=00388025962693875991&uits=1&tid=1e01d29a-c156-3986-bc14-72ec6adb1b4f&ip=0.0.0.0&ipbits=0&expire=1469253745&sparams=id,itag,source,o,uits,tid,ip,ipbits,expire&signature=989B1F047E97F4E621E88F49D3A6B1127371008F.C658701D7937F89F3498AD06AF8D3E008B1C5084&key=sj3                                                                                       
(requests kwargs: {u'url': u'https://sj.googleusercontent.com/download?id=f7d4c9b86874da5d&itag=25&source=skyjam_user_upload&o=00388025962693875991&uits=1&tid=1e01d29a-c156-3986-bc14-72ec6adb1b4f&ip=0.0.0.0&ipbits=0&expire=1469253745&sparams=id,itag,source,o,uits,tid,ip,ipbits,expire&signature=989B1F047E97F4E621E88F49D3A6B1127371008F.C658701D7937F89F3498AD06AF8D3E008B1C5084&key=sj3', u'headers': {u'X-Device-ID': u'D4:3D:7E:E4:08:49', u'Authorization': u'<omitted>', u'User-agent': u'Music Manager (1, 0, 55, 7425 HTTPS - Windows)'}, u'method': u'GET'})                                                                                                                                                                    
(response was: u'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 500 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>500.</b> <ins>That\u2019s an error.</ins>\n  <p>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://www.google.com/support/">report</A> your problem and mention this error message and the query that caused it.  <ins>That\u2019s all we know.</ins>\n')
`

**Comment by stevenewbs** [comment]
I don't seem to be hitting this error and I have been using this for a while. Does this happen on a particular song or anything? Anything that might help replicate the issue?

**Comment by stevenewbs** [comment]
From the looks of the error message this was a Google music/api issue.
